### ISSUE TITLE
Problem with JS scrips on PATH 

### ISSUE THREAD

**Issue by jeroen** [r-wasm/rwasm#6]
Some R packages [fail to build](https://github.com/r-universe/r-rust/actions/runs/6832942573/job/18803918611) because we put `/opt/webr/wasm/bin` on the PATH at build time. However this dir contains javascript tools, that the host can not execute. Is it really required to have this on the PATH?

https://github.com/r-wasm/rwasm/blob/c15083fa2f228c08c08f49dc663e87cc5f69e70b/R/build.R#L61

For example packages cannot extract a `tar.xz` file because /usr/bin/xz is masked by `/opt/webr/wasm/bin/xz`.

**Comment by georgestagg** [comment]
The `wasm/bin` directory is added to the path because some of the files in there are useful shell scripts, e.g. `gdal-config`. However, I can see that most of the files in there should not be on the `PATH`.

I think a good solution would be to update webR's Makefiles for building Wasm system libraries so that they copy any useful host-compatible scripts into `webr/host/bin`, then remove `webr/wasm/bin` from the path here and add `host/bin` instead. That should avoid JS tools like `xz` getting in the way.

I'll open a related Issue in r-wasm/webr, then return here once that's been implemented.

**Comment by shikokuchuo** [comment]
The masking appears to be solved, but now there is a `tar: This does not look like a tar archive` error - my sources are in `.tar.xz` files.

e.g. at: https://github.com/r-universe/shikokuchuo/actions/runs/7596020168/job/20689283194

I'm bringing this up as I've just been made aware that, apparently, it is possible to compile the NNG library using emscripten. I'd like to investigate what is currently possible if I can get past this install step. Thanks.

**Comment by shikokuchuo** [comment]
@georgestagg I can confirm that the issue with 'xz' at least is resolved. After a bit of tweaking to the CMake files, NNG and MbedTLS are compiling! https://github.com/r-universe/shikokuchuo/actions/runs/8639056802/job/23684720195
